import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-800">
          <div className="sticky top-0 z-10 border-b-2 border-gray-500">
            <Navbar />
          </div>
          <div className="lg:mx-64">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
